version: "3.8"

services:
  bato_qdrant:
    image: qdrant/qdrant:latest
    container_name: bato_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - bato-network

  bato_redis:
    image: redis/redis-stack:latest
    container_name: bato_redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    networks:
      - bato-network

networks:
  bato-network:
    driver: bridge
